nodeLinker: node-modules

npmScopes:
  bodhidigital:
    npmAuthToken: "${NPM_AUTH_TOKEN-DISABLED}"
    npmPublishRegistry: "https://registry.npmjs.org"
    npmRegistryServer: "https://registry.npmjs.org"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"

yarnPath: .yarn/releases/yarn-3.3.0.cjs
